# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fddaedf76bdebdd104c8e3e25974ad0555595869ddfa9401a973e367689f8aca0b575f33f6586a500d7ef35cc13ac044e64fe8882a9ab7a8a199140106ca725c

test:
  secret_key_base: 21a2051f1be54d942e988a13e2ad78c401cebdcc0a7047c7ab9a17b57cecca431ed44e54b741084a3ea82c7512ab17c46ab00489bec2b4cae15e52a8c0b2a445

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
